#!/bin/sh

set -e

files="
pixmaps/ubuntu-logo-icon.png
pixmaps/ubuntu-logo-dark.png
pixmaps/ubuntu-logo-text.png
pixmaps/ubuntu-logo-text-dark.png
plymouth/ubuntu-logo.png
"

if [ "$1" = "upgrade" ] || [ "$1" = "install" ]; then
	for item in $files 
	do
		dpkg-divert --package vanilla-distrologo --add --rename \
		--divert "/usr/share/$item"".vanilla" "/usr/share/$item"

		ln -s /usr/share/pixmaps/vanilla-logo-icon.png \
		"/usr/share/$item"
	done
fi

#DEBHELPER#